# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PumaProxy < Formula
  desc ""
  homepage ""
  version "0.0.8"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ianks/puma-proxy/releases/download/v0.0.8/puma-proxy_0.0.8_Darwin_x86_64.tar.gz"
      sha256 "9689c283d314813a85d2791e06f978f0ea00c1ca389047f5ab398e32ce6d03df"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ianks/puma-proxy/releases/download/v0.0.8/puma-proxy_0.0.8_Darwin_arm64.tar.gz"
      sha256 "e233b13f1d66916af5e3d5289c22b307a916aca751c566fc391abbbe70b8c02a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ianks/puma-proxy/releases/download/v0.0.8/puma-proxy_0.0.8_Linux_x86_64.tar.gz"
      sha256 "1709921698eb1495ca0c91a74319754c97efb3c6ebfa8d2f08f67ed0e24c95f5"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ianks/puma-proxy/releases/download/v0.0.8/puma-proxy_0.0.8_Linux_arm64.tar.gz"
      sha256 "4ae65181cbd0acfec8b97bad86853e68f113f06a935b044803e8e5bd845617a5"
    end
  end

  def install
    bin.install "puma-proxy"
  end
end
