# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PumaProxy < Formula
  desc "A simple reverse proxy for the Puma app server"
  homepage "https://github.com/ianks/puma-proxy"
  version "0.1.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ianks/puma-proxy/releases/download/v0.1.1/puma-proxy_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "28416dd18f768304d0a47f5fb8d1dbe799349471c484c9da1c3b48202ad48a70"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ianks/puma-proxy/releases/download/v0.1.1/puma-proxy_0.1.1_Darwin_arm64.tar.gz"
      sha256 "5e6068ce057027a51559aad05d6779cb13882a5bf478c4e731a02968e59cfabd"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ianks/puma-proxy/releases/download/v0.1.1/puma-proxy_0.1.1_Linux_x86_64.tar.gz"
      sha256 "2ae6bd241698e2a893fcb0224b174bc0a38c666d1b8a1bdaf90a97b4ef851fb2"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ianks/puma-proxy/releases/download/v0.1.1/puma-proxy_0.1.1_Linux_arm64.tar.gz"
      sha256 "5d3394ae1e9b701b2dc316c99587ee62e206fb8e1a22cd89a487fce4cd935c71"
    end
  end

  def install
    bin.install "puma-proxy"
  end
end
